### ISSUE TITLE
关于增加类ideal(理想点)的问题

### ISSUE THREAD

**Issue by shsty** [owen8877/Geometry#6]
ideal point 即庞加莱圆盘圆周上的点，按定义来说不属于双曲空间，应当与普通点区分开来。
可以用一个点和ideal point来表示一条射线的方向，比如用在点的平移和角的构造
用两个ideal point来表示直线

**Comment by owen8877** [comment]
ideal也可以不用单独成为一个类，可以继承complex。不过在构造直线的时候极少用到ideal point。

**Comment by shsty** [comment]
已增加ideal类
